version:              '3.7'

services:

  client:
    build:            "https://github.com/AnimusPEXUS/mqttcsep.git"
    restart:          always
    environment:
      MQTTCSEP_WORDS: Hello, cruel world
    command:          app client --broker=mqtt:1883

  server:
    build:            "https://github.com/AnimusPEXUS/mqttcsep.git"
    restart:          always
    environment:
      MQTTCSEP_WORDS: Hello, cruel world
    command:          app server --broker=mqtt:1883

  mqtt:
    image:            eclipse-mosquitto
    restart:          always
